FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/FashionStore.Api/FashionStore.Api.csproj", "src/FashionStore.Api/"]
COPY ["src/FashionStore.Core/FashionStore.Core.csproj", "src/FashionStore.Core/"]
COPY ["src/FashionStore.Infrastructure/FashionStore.Infrastructure.csproj", "src/FashionStore.Infrastructure/"]
RUN dotnet restore "src/FashionStore.Api/FashionStore.Api.csproj"
COPY . .
WORKDIR "/src/src/FashionStore.Api"
RUN dotnet build "FashionStore.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FashionStore.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FashionStore.Api.dll"]