"""add static qr gateway fields to payment

Revision ID: 62fce272acff
Revises: 0002_ci2_extra
Create Date: 2026-09-19 19:32:42.269223
"""
from alembic import op
import sqlalchemy as sa


revision = '62fce272acff'
down_revision = '0002_ci2_extra'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bitacora_sistema', 'entity',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.add_column('pago', sa.Column('qr_payload', sa.String(length=500), nullable=True))
    op.add_column('pago', sa.Column('qr_svg', sa.String(), nullable=True))
    op.add_column('pago', sa.Column('qr_png_base64', sa.String(), nullable=True))
    op.add_column('pago', sa.Column('qr_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pago', sa.Column('qr_webhook_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pago', sa.Column('qr_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pago', sa.Column('qr_verification_method', sa.String(length=20), nullable=True))
    op.add_column('pago', sa.Column('qr_manually_marked_paid', sa.Boolean(), nullable=True))
    op.add_column('pago', sa.Column('qr_webhook_payload', sa.String(), nullable=True))
    op.drop_index('ix_password_reset_token_hash', table_name='password_reset')
    op.alter_column('prenda_variante', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prenda_variante', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_product_embeddings_vector', table_name='product_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint('uq_product_embeddings_variant_id', 'product_embeddings', type_='unique')
    op.alter_column('recepcion_producto', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_usuario_email', 'usuario', type_='unique')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.alter_column('venta', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venta', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.create_unique_constraint('uq_usuario_email', 'usuario', ['email'])
    op.alter_column('recepcion_producto', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_product_embeddings_variant_id', 'product_embeddings', ['variant_id'])
    op.create_index('ix_product_embeddings_vector', 'product_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('prenda_variante', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prenda_variante', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_password_reset_token_hash', 'password_reset', ['token_hash'], unique=True)
    op.drop_column('pago', 'qr_webhook_payload')
    op.drop_column('pago', 'qr_manually_marked_paid')
    op.drop_column('pago', 'qr_verification_method')
    op.drop_column('pago', 'qr_verified_at')
    op.drop_column('pago', 'qr_webhook_received_at')
    op.drop_column('pago', 'qr_expires_at')
    op.drop_column('pago', 'qr_png_base64')
    op.drop_column('pago', 'qr_svg')
    op.drop_column('pago', 'qr_payload')
    op.alter_column('bitacora_sistema', 'entity',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###